doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        persistent: true

        server_version: '5.7'
        types:
            # HOME
            HomeDisplayType: App\DBAL\Types\Home\DisplayType
            HomeTypeType: App\DBAL\Types\Home\TypeType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
